### PR TITLE
Improved handling of empty and rank-deficient fixed effects

### LINKED ISSUE #242: Variable ordering is wrong
Basically I am getting mismatched coefficients and variables when a column is all 0's. I've included an example below showing the input data and the model result. Variable `a` is all 0's, but all the other variables should have valid coefficients and `b` does not.

I'm guessing that somehow the data for `a` gets removed because it's constant, but gets improperly added to the result. It seems like this case should either be fully supported or explicitly fail.

This example was created using MixedModels v2.2.0
```
using DataFrames, Random, MixedModels, StatsModels

rng = MersenneTwister(53);
data = DataFrames.DataFrame(
    a=repeat([0.0], 20),
    b=rand(rng, 20),
    c=rand(rng, 20),
    y=rand(rng, 20),
    category=repeat([1,2,3,4], 5)
)

categorical!(data, [:category])

f = Meta.parse("y ~ a + b + c + (1 + c | category)")
model_form = @eval StatsModels.@formula($f)
model = LinearMixedModel(model_form, data)
fit!(model)
```
Output:
```
Linear mixed model fit by maximum likelihood
 y ~ 1 + a + b + c + (1 + c | category)
   logLik    -2 logLik      AIC         BIC
 -0.63159143  1.26318286 17.26318286 25.22904105

Variance components:
            Column               Variance                  Std.Dev.         Corr.
category (Intercept)  0.00000000000000000000000000000 0.000000000000000000
         c            0.00000000000000000000022822322 0.000000000015107059   NaN
Residual              0.06236706649847829908583918268 0.249733991475886791
 Number of obs: 20; levels of grouping factors: 4

  Fixed-effects parameters:
────────────────────────────────────────────────────────
               Estimate   Std.Error     z value  P(>|z|)
────────────────────────────────────────────────────────
(Intercept)   0.286783     0.143214    2.00248    0.0452
b            -0.0        NaN         NaN          NaN
c             0.0450868    0.233915    0.192749   0.8472
a             0.212049     0.209424    1.01253    0.3113
────────────────────────────────────────────────────────
```

### LINKED ISSUE #252: OutOfMemory Error / Julia Crash for "simple" example
If I run the following lines of code, either I get an "OutOfMemory" error, or Julia crashes.

```
using MixedModels, DataFrames, Random

d3 = DataFrame()
d3.fixefA = [1,0,1,0,1,0,1,0,1]
d3.fixefB = [0,1,0,1,0,1,0,1,0]
d3.groupA = [1,0,1,0,2,0,2,0,2]
d3.groupB = [0,1,0,1,0,2,0,2,0]
d3.y = randn(MersenneTwister(42), size(d3.groupA))
categorical!(d3,:groupA)
categorical!(d3,:groupB)

f = @formula(y~0+(0+fixefA|groupA)+(0+fixefB|groupB))
mm = fit(LinearMixedModel,f,d3)
```

This is with the newest MixedModels master from github on windows10. Pinging @palday 

Full error:

```
ERROR: OutOfMemoryError()
Stacktrace:
 [1] Array at .\boot.jl:406 [inlined]
 [2] *(::LinearAlgebra.Adjoint{Float64,MixedModels.FeMat{Float64,Array{Float64,2}}}, ::ReMat{Float64,1}) at C:\Users\behinger\.julia\dev\MixedModels\src\remat.jl:233
 [3] createAL(::Array{Union{MixedModels.FeMat{Float64,S} where S<:(AbstractArray{T,2} where T), ReMat{Float64,S} where S},1}) at C:\Users\behinger\.julia\dev\MixedModels\src\linearmixedmodel.jl:225
 [4] #LinearMixedModel#35(::Dict{Symbol,Any}, ::Array{Any,1}, ::Type{LinearMixedModel}, ::StatsModels.FormulaTerm{StatsModels.Term,Tuple{StatsModels.ConstantTerm{Int64},StatsModels.FunctionTerm{typeof(|),var"#13#15",(:fixefA, :groupA)},StatsModels.FunctionTerm{typeof(|),var"#14#16",(:fixefB, :groupB)}}}, ::NamedTuple{(:fixefA, :fixefB, :groupA, :groupB, :y),Tuple{Array{Int64,1},Array{Int64,1},CategoricalArray{Int64,1,UInt32,Int64,CategoricalValue{Int64,UInt32},Union{}},CategoricalArray{Int64,1,UInt32,Int64,CategoricalValue{Int64,UInt32},Union{}},Array{Float64,1}}}) at C:\Users\behinger\.julia\dev\MixedModels\src\linearmixedmodel.jl:81
 [5] Type at .\none:0 [inlined]
 [6] #fit#37(::Array{Any,1}, ::Dict{Symbol,Any}, ::Int64, ::Bool, ::typeof(fit), ::Type{LinearMixedModel}, ::StatsModels.FormulaTerm{StatsModels.Term,Tuple{StatsModels.ConstantTerm{Int64},StatsModels.FunctionTerm{typeof(|),var"#13#15",(:fixefA, :groupA)},StatsModels.FunctionTerm{typeof(|),var"#14#16",(:fixefB, :groupB)}}}, ::NamedTuple{(:fixefA, :fixefB, :groupA, :groupB, :y),Tuple{Array{Int64,1},Array{Int64,1},CategoricalArray{Int64,1,UInt32,Int64,CategoricalValue{Int64,UInt32},Union{}},CategoricalArray{Int64,1,UInt32,Int64,CategoricalValue{Int64,UInt32},Union{}},Array{Float64,1}}}) at C:\Users\behinger\.julia\dev\MixedModels\src\linearmixedmodel.jl:115
 [7] (::StatsBase.var"#kw##fit")(::NamedTuple{(:wts, :contrasts, :verbose, :REML),Tuple{Array{Any,1},Dict{Symbol,Any},Int64,Bool}}, ::typeof(fit), ::Type{LinearMixedModel}, ::StatsModels.FormulaTerm{StatsModels.Term,Tuple{StatsModels.ConstantTerm{Int64},StatsModels.FunctionTerm{typeof(|),var"#13#15",(:fixefA, :groupA)},StatsModels.FunctionTerm{typeof(|),var"#14#16",(:fixefB, :groupB)}}}, ::NamedTuple{(:fixefA, :fixefB, :groupA, :groupB, :y),Tuple{Array{Int64,1},Array{Int64,1},CategoricalArray{Int64,1,UInt32,Int64,CategoricalValue{Int64,UInt32},Union{}},CategoricalArray{Int64,1,UInt32,Int64,CategoricalValue{Int64,UInt32},Union{}},Array{Float64,1}}}) at .\none:0
 [8] #fit#36(::Array{Any,1}, ::Dict{Symbol,Any}, ::Int64, ::Bool, ::typeof(fit), ::Type{LinearMixedModel}, ::StatsModels.FormulaTerm{StatsModels.Term,Tuple{StatsModels.ConstantTerm{Int64},StatsModels.FunctionTerm{typeof(|),var"#13#15",(:fixefA, :groupA)},StatsModels.FunctionTerm{typeof(|),var"#14#16",(:fixefB, :groupB)}}}, ::DataFrame) at C:\Users\behinger\.julia\dev\MixedModels\src\linearmixedmodel.jl:97
 [9] fit(::Type{LinearMixedModel}, ::StatsModels.FormulaTerm{StatsModels.Term,Tuple{StatsModels.ConstantTerm{Int64},StatsModels.FunctionTerm{typeof(|),var"#13#15",(:fixefA, :groupA)},StatsModels.FunctionTerm{typeof(|),var"#14#16",(:fixefB, :groupB)}}}, ::DataFrame) at C:\Users\behinger\.julia\dev\MixedModels\src\linearmixedmodel.jl:97
 [10] top-level scope at none:0
```

### PR DESCRIPTION
**Pull request by palday**
- [x] Add missing `rankUpdate!` method for `Diagonal` A by casting to `SparseMatrix`
- [x] Test for additional `rankUpdate!` method
- [x] Warn at model construction about rank deficient FE.
- [x] Real zero-dim FE support
- [x] Test for zero-dim FE support
- [x] Fix ordering issue in `coeftable` (names are now un-pivoted to match `coef` and `stderror`, but see next point.
- [x] Consistency in API for pivot. `fixef` defaults to dropping pivoted elements, while `coef`, `stderror` display treat them as `-0` \ `NaN`.
- [x] Test for correct ordering of names in rank-deficient coefficient table.
 
fixes #24, fixes #242, fixes #252.

### CODE REVIEW

**Comment by palday** [comment]
For fixing the API, the solution seems to be to note the pivoting behavior for `fixef`, `coef`, and `stderror` and add an accessor function for `cnames` that takes a pivot argument.

**Comment by palday** [comment]
Or actually, just fix the implementation of `StatsBase.coefnames(::MixedModel)` and add a parallel `fixefnames` function.

File: src/femat.jl [hunk 1]
```diff
@@ -20,10 +20,24 @@ end
...
+        rank = ch.rank
+        Xp = all(pivot .== 1:size(X, 2)) ? X : X[:, ch.piv]
+        if rank < length(pivot)
+            @warn "fixed-effects matrix is rank deficient"
+        end
+    else
+        # although it doesn't take long for an empty matrix,
+        # we can still skip the Cholesky step, which gets the rank
+        # wrong anyway
+        pivot = zeros(Int,0)
```
Comment (dmbates) [inline src/femat.jl]: Suggest
```
pivot = Int[]
```
instead.
