### PR TITLE
fix typo that changes scale

### LINKED ISSUE #713: The ftol_rel should be a small number, not a large number, right?
https://github.com/JuliaStats/MixedModels.jl/blob/9ee4a0a9f371eddf9aa68118d96c8a006f4a4d58/src/bootstrap.jl#L183

Should the new value of `ftol_rel` be `1e-8`, not `1e08`?

### PR DESCRIPTION
**Pull request by palday**
closes #713

### CODE REVIEW

File: src/bootstrap.jl [hunk 1]
```diff
@@ -180,7 +180,7 @@ families with a dispersion parameter.
 - `hide_progress` can be used to disable the progress bar. Note that the progress
 bar is automatically disabled for non-interactive (i.e. logging) contexts.
 - `optsum_overrides` is used to override values of [OptSummary](@ref) in the models
-fit during the bootstrapping process. For example, `optsum_overrides=(;ftol_rel=1e08)`
+fit during the bootstrapping process. For example, `optsum_overrides=(;ftol_rel=1e-08)`
```
Comment (ararslan) [inline src/bootstrap.jl:183]: Haha nice

**Review by ararslan — APPROVED** [review]
