### PR TITLE
Fix `simulate!` when only the estimable coefficients  are provided

### LINKED ISSUE #741: Need to adjust parametricbootstrap display for GLMMs w/o scale parameter
A Bernoulli/binomial/Poisson GLMM does not have a scale parameter and `parametricbootstrap` produces a result in which the σ values are a vector of `missing`.  The display or storage should be modified to take this into account.

Reproduce with
```julia
using MixedModels, TypedTables
contra = MixedModels.dataset(:contra)
contra = Table(contra, ch = contra.livch .≠ "0")
gm1 = let f = @formula use ~ 1 + age * ch + age^2 + urban + (1| dist & urban)
         fit(MixedModel, f, contra, Bernoulli(); nAGQ = 9)
       end
gm1samp = parametricbootstrap(2_000, gm1);
```

```julia
julia> typeof(gm1.σ)
Missing

julia> typeof(gm1samp.σ)
Vector{Missing} (alias for Array{Missing, 1})
```
Pretty much anything you try to do with `gm1samp` will throw an error.

### PR DESCRIPTION
**Pull request by palday**
closes #741

Did behavior change? Did you add need features? If so, please update NEWS.md
- [x] add entry in NEWS.md
- [x] after opening this PR, add a reference and run `docs/NEWS-update.jl` to update the cross-references.

Should we release your changes right away? If so, bump the version:
- [x] I've bumped the version appropriately

### CODE REVIEW

File: src/generalizedlinearmixedmodel.jl [hunk 1]
```diff
@@ -426,6 +426,7 @@ function GeneralizedLinearMixedModel(
             LMM.optsum,
         )
     end
+    X = view(LMM.X, :, 1:(LMM.feterm.rank))
```
Comment (ararslan) [inline src/generalizedlinearmixedmodel.jl:429]: I believe this is the same as
```suggestion
    X = fullrankx(LMM.feterm)
```

File: src/generalizedlinearmixedmodel.jl [hunk 2]
```diff
@@ -793,7 +794,7 @@ function updateη!(m::GeneralizedLinearMixedModel{T}) where {T}
     b = m.b
     u = m.u
     reterms = m.LMM.reterms
-    mul!(η, modelmatrix(m), m.β)
+    mul!(η, view(modelmatrix(m), :, 1:(m.LMM.feterm.rank)), m.β)
```
Comment (ararslan) [inline src/generalizedlinearmixedmodel.jl:797]: This is the same but IMO is easier to read/understand at a glance:
```suggestion
    mul!(η, view(modelmatrix(m), :, 1:rank(m)), m.β)
```

File: src/simulate.jl [hunk 3]
```diff
@@ -158,8 +158,8 @@ function simulate!(
     isempty(θ) || setθ!(m, θ)
 
     if length(β) ≠ length(m.feterm.piv)
-        padding = length(model.feterm.piv) - m.feterm.rank
-        append!(β, fill(-0.0, padding))
+        β = invpermute!(copyto!(fill(-0.0, length(m.feterm.piv)), β),
```
Comment (ararslan) [inline src/simulate.jl:161]: Why reassign `β` to a new array rather than adding an `invpermute!` below the existing `append!`?

File: src/simulate.jl [hunk 4]
```diff
@@ -247,11 +247,10 @@ function _simulate!(
 
     d = m.resp.d
 
-    if length(β) ≠ length(m.feterm.piv)
-        padding = length(model.feterm.piv) - m.feterm.rank
-        append!(β, fill(-0.0, padding))
+    if length(β) == length(m.feterm.piv)
+        # unlike LMM, GLMM stores the truncated, pivoted vector directly
```
Comment (ararslan) [inline src/simulate.jl:251]: Tangential to this PR but it could be convenient to have some kind of `pivot` accessor to retrieve this array.

File: test/bootstrap.jl [hunk 5]
```diff
@@ -224,16 +225,22 @@ end
...
+        @testset "$family" for family in [Normal(), Bernoulli()] 
+            model = @suppress fit(MixedModel, @formula(y ~ x + x2 + (1|z)), data, family; progress=false)
+            boot = quickboot(model, 10)
+
+            dropped_idx = model.feterm.piv[end]
+            dropped_coef = coefnames(model)[dropped_idx]
+            @test all(boot.β) do nt
+                # if we're the dropped coef, then we must be -0.0
+                # need isequal because of -0.0
+               return nt.coefname != dropped_coef || isequal(nt.β, -0.0)
```
Comment (ararslan) [inline test/bootstrap.jl:238]:
```suggestion
                return nt.coefname != dropped_coef || isequal(nt.β, -0.0)
```
Also note that you could also use `===` instead of `isequal`

**Review by ararslan — APPROVED** [review]
I had some comments/questions/suggestions but nothing blocking.

File: src/predict.jl [hunk 6]
```diff
@@ -126,7 +126,7 @@ function _predict(m::MixedModel{T}, newdata, β; new_re_levels) where {T}
         ytemp, lmm
     end
 
-    pivotmatch = mnew.feterm.piv[m.feterm.piv]
+    pivotmatch = mnew.feterm.piv[pivot(m)]
```
Comment (ararslan) [inline src/predict.jl:129]:
```suggestion
    pivotmatch = pivot(mnew)[pivot(m)]
```
