### PR TITLE
Rank update

### LINKED ISSUE #290: Error When Adding Random Slopes
I'm trying to fit a model with two grouping factors and one covariate. One has many levels (more than 20,000) and one has only a few hundred. There are ~70,000 data. I'm getting an error whenever I add a random slope of the covariate by the factor with 200 levels. The models fits without issues if I exclude random slopes.

```
ERROR: MethodError: rmulΛ!(::BlockedSparse{Float64,2,1}, ::ReMat{Float64,1}) is ambiguous. Candidates:
  rmulΛ!(A::M, B::ReMat{T,1}) where {T, M<:AbstractArray{T,2}} in MixedModels at /home/bryor/.juliapro/JuliaPro_v1.3.1-1/packages/MixedModels/qyKOf/src/remat.jl:391
  rmulΛ!(A::BlockedSparse{T,S,P}, B::ReMat{T,P}) where {T, S, P} in MixedModels at /home/bryor/.juliapro/JuliaPro_v1.3.1-1/packages/MixedModels/qyKOf/src/remat.jl:405
Possible fix, define
  rmulΛ!(::Union{M<:BlockedSparse{T,S,1}, M<:BlockedSparse{T,S,1}, M<:(BlockedSparse{T,S,1} where S)}, ::Union{ReMat{T,1}, ReMat{T,1}, ReMat{T,1}})

Stacktrace:
 [1] updateL!(::LinearMixedModel{Float64}) at /home/bryor/.juliapro/JuliaPro_v1.3.1-1/packages/MixedModels/qyKOf/src/linearmixedmodel.jl:678
 [2] #fit!#38(::Bool, ::Bool, ::typeof(fit!), ::LinearMixedModel{Float64}) at /home/bryor/.juliapro/JuliaPro_v1.3.1-1/packages/MixedModels/qyKOf/src/linearmixedmodel.jl:251
 [3] (::StatsBase.var"#kw##fit!")(::NamedTuple{(:verbose, :REML),Tuple{Bool,Bool}}, ::typeof(fit!), ::LinearMixedModel{Float64}) at ./none:0
 [4] #fit#35(::Array{Any,1}, ::Dict{Symbol,Any}, ::Bool, ::Bool, ::typeof(fit), ::Type{LinearMixedModel}, ::StatsModels.FormulaTerm{StatsModels.Term,Tuple{StatsModels.Term,StatsModels.FunctionTerm{typeof(|),var"#25#27",(:Item,)},StatsModels.FunctionTerm{typeof(|),var"#26#28",(:FreqZipfUS, :Subject)}}}, ::NamedTuple{(:RT, :FreqZipfUS, :Subject, :Item),Tuple{CSV.Column{Float64,Float64},CSV.Column{Union{Missing, Float64},Union{Missing, Float64}},CategoricalArray{Int64,1,UInt32,Int64,CategoricalValue{Int64,UInt32},Union{}},CategoricalArray{String,1,UInt32,String,CategoricalString{UInt32},Union{}}}}) at /home/bryor/.juliapro/JuliaPro_v1.3.1-1/packages/MixedModels/qyKOf/src/linearmixedmodel.jl:116
 [5] (::StatsBase.var"#kw##fit")(::NamedTuple{(:wts, :contrasts, :verbose, :REML),Tuple{Array{Any,1},Dict{Symbol,Any},Bool,Bool}}, ::typeof(fit), ::Type{LinearMixedModel}, ::StatsModels.FormulaTerm{StatsModels.Term,Tuple{StatsModels.Term,StatsModels.FunctionTerm{typeof(|),var"#25#27",(:Item,)},StatsModels.FunctionTerm{typeof(|),var"#26#28",(:FreqZipfUS, :Subject)}}}, ::NamedTuple{(:RT, :FreqZipfUS, :Subject, :Item),Tuple{CSV.Column{Float64,Float64},CSV.Column{Union{Missing, Float64},Union{Missing, Float64}},CategoricalArray{Int64,1,UInt32,Int64,CategoricalValue{Int64,UInt32},Union{}},CategoricalArray{String,1,UInt32,String,CategoricalString{UInt32},Union{}}}}) at ./none:0
 [6] #fit#34(::Array{Any,1}, ::Dict{Symbol,Any}, ::Bool, ::Bool, ::typeof(fit), ::Type{LinearMixedModel}, ::StatsModels.FormulaTerm{StatsModels.Term,Tuple{StatsModels.Term,StatsModels.FunctionTerm{typeof(|),var"#25#27",(:Item,)},StatsModels.FunctionTerm{typeof(|),var"#26#28",(:FreqZipfUS, :Subject)}}}, ::DataFrame) at /home/bryor/.juliapro/JuliaPro_v1.3.1-1/packages/MixedModels/qyKOf/src/linearmixedmodel.jl:110
 [7] fit(::Type{LinearMixedModel}, ::StatsModels.FormulaTerm{StatsModels.Term,Tuple{StatsModels.Term,StatsModels.FunctionTerm{typeof(|),var"#25#27",(:Item,)},StatsModels.FunctionTerm{typeof(|),var"#26#28",(:FreqZipfUS, :Subject)}}}, ::DataFrame) at /home/bryor/.juliapro/JuliaPro_v1.3.1-1/packages/MixedModels/qyKOf/src/linearmixedmodel.jl:110
 [8] top-level scope at REPL[32]:1
```

### PR DESCRIPTION
**Pull request by dmbates**
Clean up `rankUpdate!` methods.  In particular use Hermitian{T, Diagonal{T, Vector{T}}} instead of branching on the diagonal case in `updateL!`.  We want to use method dispatch instead of `if` statements that I had in the code.  This should be rebased on master after #329 is merged.

Closes #290.

### CODE REVIEW

File: src/linalg/rankUpdate.jl [hunk 1]
```diff
@@ -77,43 +44,39 @@ function rankUpdate!(
...
-    nz = nonzeros(A)
-    rv = rowvals(A)
-    @inbounds for j = 1:n
-        nzr = nzrange(A, j)
-        if !isempty(nzr)
-            length(nzr) == 1 || throw(ArgumentError("A*A' has off-diagonal elements"))
-            k = nzr[1]
-            dd[rv[k]] += α * abs2(nz[k])
-        end
+    all(isone.(diff(A.colptr))) || throw(ArgumentError("Columns of A must have exactly 1 nonzero"))
```
[the remark this answers is not in the document]
Comment (palday) [reply src/linalg/rankUpdate.jl:60]: Ah and I get to the next method and see that the new error message is more consistent with the error message for a different optimization.

File: src/remat.jl [hunk 2]
```diff
@@ -43,7 +43,7 @@ function _amalgamate(reterms::Vector, T::Type)
     value = ReMat{T}[]
     for (f, inds) in factordict
         if isone(length(inds))
-            push!(value, reterms[first(inds)])
+            push!(value, reterms[only(inds)])
```
Comment (palday) [inline src/remat.jl:46]: yay for `only()` :)

File: src/remat.jl [hunk 3]
```diff
@@ -374,8 +376,10 @@ function *(adjA::Adjoint{T,<:ReMat{T,S}}, B::ReMat{T,P}) where {T,S,P}
     BlockedSparse{T,S,P}(cscmat, reshape(cscmat.nzval, S, :), cscmat.colptr[1:P:(cscmat.n + 1)])
 end
 
-PCA(A::ReMat{T,1}; corr::Bool=true) where {T} =
-    PCA(corr ? reshape(abs.(vec(A.λ)),1,1) : reshape(ones(T,1),1,1), corr=corr)
+function PCA(A::ReMat{T,1}; corr::Bool=true) where {T}
+    val = ones(T, 1, 1)
+    PCA(corr ? val : abs(only(A.λ)) * val, corr=corr)
+end
```
Comment (palday) [inline src/remat.jl:382]: this helps readability nicely

File: test/linalg.jl [hunk 4]
```diff
@@ -52,6 +52,7 @@ end
     @test loglikelihood(fit!(wm1)) ≈ loglikelihood(m1)
 end
 
+#=  I don't see this testset as meaningful b/c diagonal A does not occur after amalgamation of ReMat's for the same grouping factor - D.B.
```
Comment (palday) [inline test/linalg.jl:55]: I'm trying to think of a case where diagonal A could occur. Perhaps in one of the custom model types some of the ZiF spinoff projects are working on? Maybe this is something re-visit in a few weeks to months and see if we can further trim.

File: src/linalg/rankUpdate.jl [hunk 5]
```diff
@@ -126,37 +89,23 @@ function rankUpdate!(
...
-function rankUpdate!(
-    C::Diagonal{T,S},
-    A::Diagonal{T,S},
-    α::Number = true,
-    β::Number = true,
-) where {T,S}
-    length(C.diag) == length(A.diag) || throw(DimensionMismatch("length(C.diag) ≠ length(A.diag)"))
-
-    C.diag .= β .* C.diag .+ α .* abs2.(A.diag)
+    Cdiag = β .* Cdiag .+ α .* abs2.(A.diag)
```
[the remark this answers is not in the document]
Comment (palday) [reply src/linalg/rankUpdate.jl:99]: Ah, of course, this is in the commented-out function. :facepalm:

Comment (palday) [inline src/linalg/rankUpdate.jl:99]:
```suggestion
    Cdiag .= β .* Cdiag .+ α .* abs2.(A.diag)
```

**Comment by dmbates** [comment]
> If I understand everything correctly, then it looks pretty good. I have one question about assignment vs. dot assignment in a single method that needs attention, everything else is small.
> 
> The two big changes that I didn't comment on are:
> 
>     1. No default values for alpha and beta in the rank update methods. I think this is fine, but this is definitely a breaking change (admittedly on non-exported methods), so it's a good thing to get in now before the big release. Is this also in line with the related methods in LinearAlgebra?
> 
>     2. Removal of a catch-all `rankUpdate!` method. I'm wondering if we should still have that in there. Or maybe even something 'dumber', such as
> 
> 
> ```julia
> function rankUpdate(A::Any, B::Any, alpha, beta) 
>    error("We haven't implemented a method for $(typeof(A)), $(typeof(B)). Please file an issue on GitHub")
> end
> ```

I don't see the benefit of adding a "catch-all" method to generate an error.  Not having a method has the same effect, doesn't it?

**Comment by dmbates** [comment]
> If I understand everything correctly, then it looks pretty good. I have one question about assignment vs. dot assignment in a single method that needs attention, everything else is small.
> 
> The two big changes that I didn't comment on are:
> 
>     1. No default values for alpha and beta in the rank update methods. I think this is fine, but this is definitely a breaking change (admittedly on non-exported methods), so it's a good thing to get in now before the big release. Is this also in line with the related methods in LinearAlgebra?

I felt that this generic would be internal to the package and I dropped the default values for alpha and beta because there is only one call to generic in the package.  It seemed it was easier to specify the values there than to add defaults for all the methods.

**Comment by palday** [comment]
> > If I understand everything correctly, then it looks pretty good. I have one question about assignment vs. dot assignment in a single method that needs attention, everything else is small.
> > The two big changes that I didn't comment on are:
> > ```
> > 1. No default values for alpha and beta in the rank update methods. I think this is fine, but this is definitely a breaking change (admittedly on non-exported methods), so it's a good thing to get in now before the big release. Is this also in line with the related methods in LinearAlgebra?
> > 
> > 2. Removal of a catch-all `rankUpdate!` method. I'm wondering if we should still have that in there. Or maybe even something 'dumber', such as
> > ```
> > 
> > 
> > ```julia
> > function rankUpdate(A::Any, B::Any, alpha, beta) 
> >    error("We haven't implemented a method for $(typeof(A)), $(typeof(B)). Please file an issue on GitHub")
> > end
> > ```
> 
> I don't see the benefit of adding a "catch-all" method to generate an error. Not having a method has the same effect, doesn't it?

For us, yes. But for the average user, a `MethodError` followed by a stacktrace is big and scary and potentially looks like a bug. An error with "we haven't implemented this yet" seems less scary. But then again, both will generate huge stacktraces and that's probably the hardest thing for normal users anyway.

Ultimately, I'm neutral. Do we have a "normal" person we can ask?

File: test/linalg.jl (hunk 4 above)
Comment (dmbates) [reply test/linalg.jl:55]: It is best to think of how `rankUpdate!` gets called.  After pre- and post-multiplication by Lambda and inflation of the diagonal the `rankUpdate!` methods get called with `C` being one of the diagonal blocks and `A` being a block to the left of `C`.  So `C` is `m.L[Block(2,2)]` or higher because there are no blocks to the left of `m.L[Block(1,1)]`.  The cases that matter are when there is more than one grouping factor for the random effects.  If `A` were to be diagonal then it would need to be generated from two scalar random-effects terms, as in `(1|G) + (1|H)` and the number of levels of `G` and `H` would need to be equal and the levels would match.  You can get that from `(1|G) + (0+x|G)` but that is now collapsed to a single r.e. term either through `zerocorr(1+x|G)` or by amalgamation of the random effects terms.  So I don't think there will be real-life cases where `A` is diagonal.  `C` is always a square matrix and either `Diagonal` or `UniformBlockDiagonal` or, through fill-in, `Dense`.   The only special cases for `A` are `Dense`, `SparseMatrixCSC` or, in a new branch that I haven't pushed yet, `KHotColumn`.  The last one is a special type of sparse matrix generated by nested grouping factors for vector-valued random effects where each column of `A` has exactly `K` adjacent non-zeros.

**Comment by dmbates** [comment]
> > > If I understand everything correctly, then it looks pretty good. I have one question about assignment vs. dot assignment in a single method that needs attention, everything else is small.
> > > The two big changes that I didn't comment on are:
> > > ```
> > > 1. No default values for alpha and beta in the rank update methods. I think this is fine, but this is definitely a breaking change (admittedly on non-exported methods), so it's a good thing to get in now before the big release. Is this also in line with the related methods in LinearAlgebra?
> > > 
> > > 2. Removal of a catch-all `rankUpdate!` method. I'm wondering if we should still have that in there. Or maybe even something 'dumber', such as
> > > ```
> > > 
> > > 
> > > ```julia
> > > function rankUpdate(A::Any, B::Any, alpha, beta) 
> > >    error("We haven't implemented a method for $(typeof(A)), $(typeof(B)). Please file an issue on GitHub")
> > > end
> > > ```
> > 
> > 
> > I don't see the benefit of adding a "catch-all" method to generate an error. Not having a method has the same effect, doesn't it?
> 
> For us, yes. But for the average user, a `MethodError` followed by a stacktrace is big and scary and potentially looks like a bug. An error with "we haven't implemented this yet" seems less scary. But then again, both will generate huge stacktraces and that's probably the hardest thing for normal users anyway.
> 
> Ultimately, I'm neutral. Do we have a "normal" person we can ask?

I would value the opinions of either @christinabergmann or @debruine

**Comment by dmbates** [comment]
> > > > If I understand everything correctly, then it looks pretty good. I have one question about assignment vs. dot assignment in a single method that needs attention, everything else is small.
> > > > The two big changes that I didn't comment on are:
> > > > ```
> > > > 1. No default values for alpha and beta in the rank update methods. I think this is fine, but this is definitely a breaking change (admittedly on non-exported methods), so it's a good thing to get in now before the big release. Is this also in line with the related methods in LinearAlgebra?
> > > > 
> > > > 2. Removal of a catch-all `rankUpdate!` method. I'm wondering if we should still have that in there. Or maybe even something 'dumber', such as
> > > > ```
> > > > 
> > > > 
> > > > ```julia
> > > > function rankUpdate(A::Any, B::Any, alpha, beta) 
> > > >    error("We haven't implemented a method for $(typeof(A)), $(typeof(B)). Please file an issue on GitHub")
> > > > end
> > > > ```
> > > 
> > > 
> > > I don't see the benefit of adding a "catch-all" method to generate an error. Not having a method has the same effect, doesn't it?
> > 
> > 
> > For us, yes. But for the average user, a `MethodError` followed by a stacktrace is big and scary and potentially looks like a bug. An error with "we haven't implemented this yet" seems less scary. But then again, both will generate huge stacktraces and that's probably the hardest thing for normal users anyway.

In retrospect I think it is fine to go ahead with adding a fallback-error method like this.  Would you (@palday)  be willing to add a test to ensure test coverage?

**Comment by palday** [comment]
@dmbates I'll take care of it. :smile:

File: test/linalg.jl (hunk 4 above)
Comment (palday) [reply test/linalg.jl:61]: Right, so the only way that this could occur would be if someone had two identical grouping variables so that they wouldn't be amalgamated. Until we see a legitimate use case for that, I think we can safely ignore that possibility.

Thanks for the refresher! :smile:

**Comment by palday** [comment]
@dmbates If you're happy with the new error message, please squash and merge.
